export default {
  USERS_GET_REQUEST: 'users/USERS_GET_REQUEST',
  USERS_GET_FAILURE: 'users/USERS_GET_FAILURE',
  USERS_GET_SUCCESS: 'users/USERS_GET_SUCCESS',
  USERS_MODIFY_REQUEST: 'users/USERS_MODIFY_REQUEST',
  USERS_MODIFY_FAILURE: 'users/USERS_MODIFY_FAILURE',
  USERS_MODIFY_SUCCESS: 'users/USERS_MODIFY_SUCCESS',
  USERS_CLEAR: 'users/USERS_CLEAR',
};
