export default {
  NOTIFICATION_REQUEST: 'notification/NOTIFICATION_REQUEST',
  NOTIFICATION_FAILURE: 'notification/NOTIFICATION_FAILURE',
  NOTIFICATION_SUCCESS: 'notification/NOTIFICATION_SUCCESS',
  NOTIFICATION_SEND_REQUEST: 'notification/NOTIFICATION_SEND_REQUEST',
  NOTIFICATION_SEND_FAILURE: 'notification/NOTIFICATION_SEND_FAILURE',
  NOTIFICATION_SEND_SUCCESS: 'notification/NOTIFICATION_SEND_SUCCESS',
  NOTIFICATION_CLEAR: 'notification/NOTIFICATION_CLEAR',
};
