export default {
  RESERVE_REQUEST: 'book/RESERVE_REQUEST',
  RESERVE_FAILURE: 'book/RESERVE_FAILURE',
  RESERVE_SUCCESS: 'book/RESERVE_SUCCESS',
  RESERVE_DELETE_REQUEST: 'book/RESERVE_DELETE_REQUEST',
  RESERVE_DELETE_FAILURE: 'book/RESERVE_DELETE_FAILURE',
  RESERVE_DELETE_SUCCESS: 'book/RESERVE_DELETE_SUCCESS',
  RESERVE_CLEAR: 'book/RESERVE_CLEAR',
};
