import React, {useState, useRef, useEffect} from 'react';
import {
  Text,
  View,
  StyleSheet,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Keyboard,
  ActivityIndicator,
  Alert,
} from 'react-native';
import {useDispatch, useSelector} from 'react-redux';

// Components
import Touchable from '../../../../components/Touchable';

// Extras
import {colors} from '../../../../utils/constants';
import selectors from '../../../../reducers/classes/selectors';
import actions from '../../../../reducers/classes/actions';
import createMAsive from '../../../../actions/classes/createMasive';

const classes = [
  {
    day: 0,
    dayText: 'Lunes',
    time: '08:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Localizada',
    area: 'MALVIN',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '09:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Fuera calorias',
    area: 'MALVIN',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '10:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Gap',
    area: 'MALVIN',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '11:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Pilates',
    area: 'MALVIN',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '15:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Localizada',
    area: 'MALVIN',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '16:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Aero Local',
    area: 'MALVIN',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '18:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Aero Local',
    area: 'MALVIN',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '19:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Super Local',
    area: 'MALVIN',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '08:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'MALVIN',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '10:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Pilates',
    area: 'MALVIN',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '11:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Zumba',
    area: 'MALVIN',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '18:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Aero Local',
    area: 'MALVIN',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '19:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Strong',
    area: 'MALVIN',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '08:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Aero Local',
    area: 'MALVIN',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '09:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'MALVIN',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '10:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Super Local',
    area: 'MALVIN',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '11:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Pilates',
    area: 'MALVIN',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '15:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Super Local',
    area: 'MALVIN',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '16:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Step + Local',
    area: 'MALVIN',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '18:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Perdida de Peso Abdomen',
    area: 'MALVIN',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '08:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Fuera calorias',
    area: 'MALVIN',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '10:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Pilates',
    area: 'MALVIN',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '11:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Zumba',
    area: 'MALVIN',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '18:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'MALVIN',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '19:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Fuera calorias',
    area: 'MALVIN',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '08:00',
    quota: 25,
    type: 'FITNESS',
    name: 'GAP',
    area: 'MALVIN',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '09:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Super Local',
    area: 'MALVIN',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '10:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Aero Local',
    area: 'MALVIN',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '11:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Pilates Stretching',
    area: 'MALVIN',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '15:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'MALVIN',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '16:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Localizada',
    area: 'MALVIN',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '18:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Fuera calorias',
    area: 'MALVIN',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '19:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'MALVIN',
  },
  {
    day: 5,
    dayText: 'Sábado',
    time: '09:00',
    quota: 25,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'MALVIN',
  },
  {
    day: 5,
    dayText: 'Sábado',
    time: '10:30',
    quota: 25,
    type: 'FITNESS',
    name: 'Fuera calorias',
    area: 'MALVIN',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '08:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Fuera calorias',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '09:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Localizada',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '11:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Pilates',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '17:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Pilates',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '18:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '19:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Localizada',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '08:00',
    quota: 24,
    type: 'FITNESS',
    name: 'GAP',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '09:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Strong',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '11:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Zumba',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '18:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Super Local',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '20:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Entr. Funcional',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '08:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Super Local',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '09:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '11:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Pilates',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '17:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Pilates',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '18:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Fuera calorias',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '19:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '08:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Aero Local',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '09:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Super Local',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '11:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Zumba',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '18:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Localizada',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '20:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Entr. Funcional',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '08:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Local',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '09:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Fuera calorias',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '11:00',
    quota: 24,
    type: 'FITNESS',
    name: 'Pilates Stretching',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '18:30',
    quota: 24,
    type: 'FITNESS',
    name: 'Glúteos Perfectos',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '08:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '09:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '10:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '12:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '13:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '14:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '15:45',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '17:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '18:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 0,
    dayText: 'Lunes',
    time: '19:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '07:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '08:45',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '10:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '11:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '12:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '15:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '16:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '17:45',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '19:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 1,
    dayText: 'Martes',
    time: '20:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '08:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '09:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '10:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '12:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '13:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '14:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '15:45',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '17:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '18:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 2,
    dayText: 'Miércoles',
    time: '19:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '07:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '08:45',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '10:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '11:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '12:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '15:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '16:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '17:45',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '19:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 3,
    dayText: 'Jueves',
    time: '20:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '08:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '09:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '10:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '12:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '13:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '14:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '15:45',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '17:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '18:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 4,
    dayText: 'Viernes',
    time: '19:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 5,
    dayText: 'Sábado',
    time: '09:00',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 5,
    dayText: 'Sábado',
    time: '10:15',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
  {
    day: 5,
    dayText: 'Sábado',
    time: '11:30',
    quota: 16,
    type: 'SPINNING',
    name: 'SPINNING',
    area: 'CARRASCO',
  },
];

const Create = ({navigation}) => {
  const {isFetching, response} = useSelector(state => ({
    isFetching: selectors.isFetching(state),
    response: selectors.getResponse(state),
  }));
  const dispatch = useDispatch();
  const scrollRef = useRef();

  const onSubmit = () =>
    Alert.alert(
      'Crear clase masiva',
      '¿Estas seguro que quieres crear las clases? Si ya existen se volverán a crear (recomendamos crearlas los días Lunes y luego verificar que existan)',
      [
        {
          text: 'Si',
          onPress: () => dispatch(createMAsive(classes, navigation)),
        },
        {
          text: 'No',
          onPress: () => {},
        },
      ],
    );

  const handleKeyboard = () => {
    scrollRef.current.scrollToEnd({animated: true});
  };

  useEffect(() => {
    Keyboard.addListener('keyboardDidShow', handleKeyboard);
    return () => {
      Keyboard.removeListener('keyboardDidShow', handleKeyboard);
    };
  }, []);

  useEffect(() => {
    if (response.isError && response.message) {
      Alert.alert('Crear clases masivas', response.message);
      dispatch(actions.clear());
    }
  }, [response]);

  return (
    <KeyboardAvoidingView
      style={styles.keyContent}
      behavior={Platform.OS === 'ios' ? 'padding' : 'padding'}
      keyboardVerticalOffset={Platform.OS === 'ios' ? 60 : 60}
      enabled={Platform.OS === 'ios' ? true : false}>
      <ScrollView
        ref={scrollRef}
        style={styles.container}
        contentContainerStyle={styles.scrollContainer}
        keyboardShouldPersistTaps="handled">
        <View style={styles.content}>
          <Text style={styles.title}>Crear clases para la semana</Text>
          <Text style={styles.title}>(Lunes a domingo)</Text>
          <Text style={styles.title}>basados en el archivo Excel </Text>
        </View>
        <Touchable highlight style={styles.button} onPress={onSubmit}>
          {isFetching ? (
            <ActivityIndicator color={colors.white} size={30} />
          ) : (
            <Text style={styles.buttonText}>Crear clases</Text>
          )}
        </Touchable>
      </ScrollView>
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  keyContent: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: colors.white,
    width: '100%',
  },
  scrollContainer: {
    flexGrow: 1,
  },
  content: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logo: {
    alignItems: 'center',
    width: '100%',
  },
  image: {
    height: 100,
  },
  title: {
    marginVertical: 20,
    fontSize: 24,
    textAlign: 'center',
  },
  input: {
    width: '80%',
    marginVertical: 10,
    height: 40,
    borderWidth: 1,
    borderColor: colors.blue,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 20,
  },
  button: {
    width: '100%',
    paddingVertical: 20,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  buttonInput: {
    width: '80%',
    marginVertical: 10,
    height: 40,
    borderWidth: 1,
    borderColor: colors.blue,
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  buttonInputText: {
    fontSize: 16,
    color: colors.black,
  },
  picker: {
    width: '80%',
    marginVertical: 5,
    fontSize: 16,
  },
  row: {
    width: '80%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    fontSize: 16,
    textAlign: 'left',
    marginVertical: 20,
    width: '80%',
  },
  date: {
    width: '100%',
  },
});

export default Create;
